corrected a spelling mistake
ballerina-platform/ballerina-examples pull request #1047
Opened 2018-09-25 15:53 UTC by Varuni-Punchihewa

## Purpose
> corrected the spelling mistake in "instaed" to "instead".

2018-09-25 16:07 UTC, Shan1024 approved these changes

2018-09-25 16:19 UTC, Shan1024 requested changes
Can you change the commit message since the current commit message does not follow the conventions we use?
Eg - 
Correct a spelling mistake 
Fix a typo

2018-09-25 16:24 UTC, anupama-pathirage approved these changes

2018-09-27 04:36 UTC, Shan1024 approved these changes

2018-09-27 05:23 UTC, merged